// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu21X0r4Q9_QWWZCbd2docEUqAwVVFLGY',
    appId: '1:335259620306:web:28ec85b0d15a0feb1cae0b',
    messagingSenderId: '335259620306',
    projectId: 'ecommercebyvinay',
    authDomain: 'ecommercebyvinay.firebaseapp.com',
    storageBucket: 'ecommercebyvinay.appspot.com',
    measurementId: 'G-WH81T18ESX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWlLQpdf_Mx_NlVOB_hQAGM9_r-nXKSFk',
    appId: '1:335259620306:android:b22027944641ba381cae0b',
    messagingSenderId: '335259620306',
    projectId: 'ecommercebyvinay',
    storageBucket: 'ecommercebyvinay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCosTiUcHgDwdT30pgwUeBrMX5P8C12m5I',
    appId: '1:335259620306:ios:99ae714f5fb094881cae0b',
    messagingSenderId: '335259620306',
    projectId: 'ecommercebyvinay',
    storageBucket: 'ecommercebyvinay.appspot.com',
    iosClientId: '335259620306-qrm8e6v3r2huapna3dtu3s4jfru0d9au.apps.googleusercontent.com',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCosTiUcHgDwdT30pgwUeBrMX5P8C12m5I',
    appId: '1:335259620306:ios:99ae714f5fb094881cae0b',
    messagingSenderId: '335259620306',
    projectId: 'ecommercebyvinay',
    storageBucket: 'ecommercebyvinay.appspot.com',
    iosClientId: '335259620306-qrm8e6v3r2huapna3dtu3s4jfru0d9au.apps.googleusercontent.com',
    iosBundleId: 'com.example.emartApp',
  );
}
